import {createContext,useContext,useEffect,useState} from 'react';
import {Routes,Route,Link,NavLink,useNavigate,useParams,Navigate} from 'react-router-dom';
import './styles.css';

const API=(import.meta.env.VITE_API_URL||'http://localhost:5000/api').trim();
const normalizedAPI=API.endsWith('/api')?API:API+'/api';
const API_ORIGIN=normalizedAPI.replace(/\/api\/?$/,'');
function mediaUrl(value=''){
  const src=String(value||'').trim();
  if(!src) return '';
  if(/^https?:\/\//i.test(src)){
    try{
      const u=new URL(src);
      if(['localhost','127.0.0.1'].includes(u.hostname)) return API_ORIGIN+u.pathname+u.search;
    }catch{}
    return src;
  }
  if(src.startsWith('//')) return window.location.protocol+src;
  return API_ORIGIN+'/'+src.replace(/^\/+/,'').replace(/^uploads\//,'uploads/');
}
async function req(path,opt={}) {
  const url=normalizedAPI+path;
  try {
    const r=await fetch(url,{credentials:'include',headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});
    const contentType=r.headers.get('content-type')||'';
    const d=contentType.includes('application/json')?await r.json().catch(()=>({})):await r.text().catch(()=> '');
    if(!r.ok){
      const serverMessage=typeof d==='string'?d.replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim():d.message;
      const error=new Error(serverMessage||`Request failed (HTTP ${r.status})`);
      error.status=r.status;error.code=d?.code;error.url=url;throw error;
    }
    return d;
  } catch(error) {
    if(error instanceof TypeError) {
      const networkError=new Error('Unable to reach the Cartiva API. Check the Render backend and frontend API URL.');
      networkError.code='NETWORK_ERROR';networkError.url=url;throw networkError;
    }
    throw error;
  }
}
const api={get:p=>req(p),post:(p,b)=>req(p,{method:'POST',body:JSON.stringify(b)}),patch:(p,b)=>req(p,{method:'PATCH',body:JSON.stringify(b)}),del:p=>req(p,{method:'DELETE'}),upload:async(files)=>{const fd=new FormData();[...files].forEach(f=>fd.append('images',f));const url=normalizedAPI+'/uploads';try{const r=await fetch(url,{method:'POST',credentials:'include',body:fd});const contentType=r.headers.get('content-type')||'';const d=contentType.includes('application/json')?await r.json().catch(()=>({})):await r.text().catch(()=> '');if(!r.ok){const serverMessage=typeof d==='string'?d.replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim():d.message;const error=new Error(serverMessage||`Upload failed (HTTP ${r.status})`);error.status=r.status;error.code=d?.code;error.url=url;throw error;}return d.urls;}catch(error){if(error instanceof TypeError){const networkError=new Error('Unable to reach the Cartiva API. Check the Render backend and frontend API URL.');networkError.code='NETWORK_ERROR';networkError.url=url;throw networkError;}throw error;}}};

const AuthContext=createContext(null); const CartContext=createContext(null);
function AuthProvider({children}){const[u,setU]=useState(null),[loading,setLoading]=useState(true);useEffect(()=>{api.get('/auth/me').then(x=>setU(x.user)).catch(()=>{}).finally(()=>setLoading(false))},[]);const value={user:u,loading,login:async f=>{const x=await api.post('/auth/login',f);setU(x.user);return x.user},ownerLogin:async code=>{const x=await api.post('/auth/owner-login',{code});setU(x.user);return x.user},register:async f=>{const x=await api.post('/auth/register',f);setU(x.user);return x.user},logout:async()=>{await api.post('/auth/logout',{});setU(null)}};return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>}
function CartProvider({children}){const[x,setX]=useState(()=>JSON.parse(localStorage.getItem('cartiva_cart')||'[]'));const save=v=>{setX(v);localStorage.setItem('cartiva_cart',JSON.stringify(v))};const value={items:x,total:x.reduce((s,i)=>s+i.price*i.quantity,0),add:p=>save(x.some(i=>i.productId===p._id)?x.map(i=>i.productId===p._id?{...i,quantity:i.quantity+1}:i):x.concat({productId:p._id,name:p.name,price:p.price,image:p.images?.[0]||'',quantity:1})),change:(id,n)=>save(n<1?x.filter(i=>i.productId!==id):x.map(i=>i.productId===id?{...i,quantity:n}:i)),remove:id=>save(x.filter(i=>i.productId!==id)),clear:()=>save([])};return <CartContext.Provider value={value}>{children}</CartContext.Provider>}
function useAuth(){return useContext(AuthContext)}
function useCart(){return useContext(CartContext)}
function Layout({children}){const{user,logout}=useAuth(),{items}=useCart();return <><header><Link className="logo" to="/">Cartiva<span>.</span></Link><nav><NavLink to="/">Shop</NavLink>{user?.role==='seller'?<NavLink to="/seller">Seller Hub</NavLink>:user?.role==='owner'?<NavLink to="/owner">Owner Control</NavLink>:user&&<NavLink to="/orders">Orders</NavLink>}{user&&<NavLink to="/notifications">Notifications</NavLink>}{!user?<><NavLink to="/login">Login</NavLink><NavLink className="outline" to="/register">Join</NavLink></>:<button onClick={logout}>Logout</button>}<NavLink to="/cart">Bag <b>{items.length}</b></NavLink></nav></header>{children}<footer>Cartiva · Direct marketplace for independent sellers.</footer></>}
function Guard({role,children}){const{user,loading}=useAuth();if(loading)return <div className="loading">Loading Cartiva…</div>;if(!user)return <Navigate to="/login"/>;if(role&&user.role!==role)return <Navigate to="/"/>;return children}

function Product({p}){const{add}=useCart();return <article className="card"><Link className="photo" to={'/products/'+p._id}>{p.images?.[0]?<img src={mediaUrl(p.images?.[0])} alt={p.name}/>:<span>CARTIVA</span>}</Link><div className="cardbody"><small>{p.category}</small><h3>{p.name}</h3><p>Sold by {p.seller?.name||'Independent seller'}</p><div className="row"><strong>₹{p.price.toLocaleString('en-IN')}</strong><button onClick={()=>add(p)}>Add</button></div></div></article>}
function Home(){const[p,setP]=useState([]),[q,setQ]=useState('');const load=()=>api.get('/products?search='+encodeURIComponent(q)).then(x=>setP(x.products));useEffect(()=>{load()},[]);return <main><section className="hero"><div><small>THE DIRECT MARKETPLACE</small><h1>Good products.<br/><i>Real sellers.</i></h1><p>Cartiva connects independent sellers directly with customers — simple shopping without the warehouse middleman.</p><Link className="dark" to="/register">Start shopping</Link></div><div className="hero-card"><span>01</span><b>Independent sellers</b><p>Discover products from people and small businesses.</p></div></section><section className="shopbar"><div><small>MARKETPLACE</small><h2>Explore products</h2></div><form onSubmit={e=>{e.preventDefault();load()}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products…"/><button>Search</button></form></section>{p.length?<section className="grid">{p.map(x=><Product key={x._id} p={x}/>)}</section>:<div className="empty">No products yet. Sellers can publish listings from Seller Hub.</div>}</main>}
function Auth({register=false,owner=false}){const{login,ownerLogin,register:signup}=useAuth(),nav=useNavigate(),[role,setRole]=useState('customer'),[f,setF]=useState({name:'',email:'',phone:'',password:'',code:''}),[err,setErr]=useState(''),[errCode,setErrCode]=useState('');async function go(e){e.preventDefault();setErr('');setErrCode('');try{const u=owner?await ownerLogin(f.code):(register?await signup({...f,role}):await login({email:f.email,password:f.password}));nav(u.role==='owner'?'/owner':u.role==='seller'?'/seller':'/')}catch(e){setErr(e.message);setErrCode(e.code||'')}}return <div className="auth"><div className="authbox owner-authbox">{owner?<><small>CARTIVA OWNER CONTROL</small><h1>Owner access</h1><p>Enter the private authentication code to manage marketplace listings.</p><form onSubmit={go}><label>Authentication code<input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{4}" maxLength="4" required value={f.code} onChange={e=>setF({...f,code:e.target.value.replace(/\D/g,'').slice(0,4)})} placeholder="••••"/></label>{err&&<div className="error">{err}</div>}<button className="dark">Enter owner control</button></form><p className="switch"><Link to="/login">← Back to customer / seller login</Link></p></>:<><small>CARTIVA ACCOUNT</small><h1>{register?'Create your account':'Welcome back'}</h1><p>{register?'Choose Customer or Seller.':'Sign in to continue.'}</p>{register&&<div className="roles"><button className={role==='customer'?'sel':''} type="button" onClick={()=>setRole('customer')}><b>Customer</b><span>Browse & order</span></button><button className={role==='seller'?'sel':''} type="button" onClick={()=>setRole('seller')}><b>Seller</b><span>List products & fulfil orders</span></button></div>}<form onSubmit={go}>{register&&<label>Name<input required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label>}<label>Email<input type="email" required value={f.email} onChange={e=>setF({...f,email:e.target.value})}/></label>{register&&<label>Phone<input value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/></label>}<label>Password<input type="password" minLength="8" required value={f.password} onChange={e=>setF({...f,password:e.target.value})}/></label>{err&&<div className="error"><div>{err}</div>{register&&errCode==='EMAIL_EXISTS'&&<Link to="/login">Sign in to your existing account →</Link>}</div>}<button className="dark">{register?'Create account':'Sign in'}</button></form><p className="switch"><Link to={register?'/login':'/register'}>{register?'Already registered? Sign in':'New to Cartiva? Create account'}</Link></p><p className="switch owner-link"><Link to="/owner-login">Owner access →</Link></p></>}</div></div>}
function Details(){const{id}=useParams(),{add}=useCart(),[p,setP]=useState(null);useEffect(()=>{api.get('/products/'+id).then(x=>setP(x.product))},[id]);if(!p)return <div className="loading">Loading…</div>;return <main className="page"><Link to="/">← Back</Link><section className="detail"><div className="detailphoto">{p.images?.[0]?<img src={mediaUrl(p.images?.[0])} alt={p.name}/>:<span>CARTIVA</span>}</div><div><small>{p.category}</small><h1>{p.name}</h1><p>Sold by <b>{p.seller?.name}</b></p><strong className="price">₹{p.price.toLocaleString('en-IN')}</strong><p className="desc">{p.description}</p><p>{p.stock} in stock</p><button className="dark" disabled={!p.stock} onClick={()=>add(p)}>Add to cart</button></div></section></main>}
function Cart(){const{items,total,change,remove}=useCart(),{user}=useAuth(),nav=useNavigate();if(!items.length)return <main className="empty page"><h1>Your bag is empty</h1><Link className="dark" to="/">Continue shopping</Link></main>;const fee=total>=999?0:49;return <main className="page"><small>YOUR BAG</small><h1>Review your items</h1><div className="cartlayout"><section>{items.map(i=><div className="cartitem" key={i.productId}><div className="mini">{i.image?<img src={mediaUrl(i.image)}/>: 'C'}</div><div><h3>{i.name}</h3><p>₹{i.price.toLocaleString('en-IN')}</p><div className="qty"><button onClick={()=>change(i.productId,i.quantity-1)}>−</button><b>{i.quantity}</b><button onClick={()=>change(i.productId,i.quantity+1)}>+</button><button onClick={()=>remove(i.productId)}>Remove</button></div></div></div>)}</section><aside className="summary"><small>SUMMARY</small><div><span>Subtotal</span><b>₹{total.toLocaleString('en-IN')}</b></div><div><span>Delivery</span><b>{fee?'₹49':'Free'}</b></div><hr/><div><b>Total</b><strong>₹{(total+fee).toLocaleString('en-IN')}</strong></div><button className="dark" onClick={()=>nav(user?'/checkout':'/login')}>{user?'Checkout':'Sign in to checkout'}</button></aside></div></main>}
function Checkout(){const{items,total,clear}=useCart(),nav=useNavigate(),[f,setF]=useState({fullName:'',phone:'',addressLine1:'',addressLine2:'',city:'',state:'',postalCode:''}),[err,setErr]=useState('');async function go(e){e.preventDefault();try{await api.post('/orders',{items,delivery:f,paymentMethod:'cod'});clear();nav('/orders')}catch(e){setErr(e.message)}}return <main className="page narrow"><small>CHECKOUT</small><h1>Delivery details</h1><p>Products from different sellers are split into seller-specific orders automatically.</p><form className="checkout" onSubmit={go}><div className="twocol"><label>Full name<input required value={f.fullName} onChange={e=>setF({...f,fullName:e.target.value})}/></label><label>Phone<input required value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/></label></div><label>Address<input required value={f.addressLine1} onChange={e=>setF({...f,addressLine1:e.target.value})}/></label><label>Apartment / landmark<input value={f.addressLine2} onChange={e=>setF({...f,addressLine2:e.target.value})}/></label><div className="twocol"><label>City<input required value={f.city} onChange={e=>setF({...f,city:e.target.value})}/></label><label>State<input required value={f.state} onChange={e=>setF({...f,state:e.target.value})}/></label></div><label>Postal code<input required value={f.postalCode} onChange={e=>setF({...f,postalCode:e.target.value})}/></label><label>Payment<select disabled><option>Cash on Delivery</option></select></label>{err&&<div className="error">{err}</div>}<button className="dark">Place order</button></form></main>}
function Orders(){const{user}=useAuth(),[o,setO]=useState([]);const load=()=>api.get('/orders/mine').then(x=>setO(x.orders));useEffect(()=>{load()},[]);async function status(id,s){await api.patch('/orders/'+id+'/status',{status:s});load()}return <main className="page"><small>{user.role==='seller'?'SELLER ORDERS':'ORDER HISTORY'}</small><h1>{user.role==='seller'?'Incoming orders':'Your orders'}</h1><div className="orders">{o.length?o.map(x=><article className="order" key={x._id}><div className="orderhead"><div><small>{x.orderNumber}</small><h3>{user.role==='seller'?'Customer: '+x.customer?.name:'Seller: '+x.seller?.name}</h3></div><span>{x.status}</span></div>{x.items.map(i=><div className="orderline" key={i.product}><span>{i.name} × {i.quantity}</span><b>₹{(i.price*i.quantity).toLocaleString('en-IN')}</b></div>)}<div className="orderfoot"><span>{x.delivery.city}, {x.delivery.state} · COD</span><strong>₹{x.total.toLocaleString('en-IN')}</strong></div>{user.role==='seller'&&<select value={x.status} onChange={e=>status(x._id,e.target.value)}>{['pending','confirmed','shipped','delivered','cancelled'].map(s=><option key={s}>{s}</option>)}</select>}</article>):<div className="empty">No orders yet.</div>}</div></main>}
function Notifications(){const[n,setN]=useState([]);const load=()=>api.get('/notifications').then(x=>setN(x.notifications));useEffect(()=>{load()},[]);async function read(id){await api.patch('/notifications/'+id+'/read',{});load()}return <main className="page"><small>INBOX</small><h1>Notifications</h1><div className="notifications">{n.length?n.map(x=><button className={x.read?'note read':'note'} key={x._id} onClick={()=>!x.read&&read(x._id)}><b>{x.title}</b><span>{x.message}</span><small>{new Date(x.createdAt).toLocaleString('en-IN')}</small></button>):<div className="empty">No notifications.</div>}</div></main>}
function Seller(){
  const[p,setP]=useState([]),[o,setO]=useState([]),[edit,setEdit]=useState(null),
    [f,setF]=useState({name:'',description:'',price:'',category:'',stock:'',images:''}),
    [files,setFiles]=useState([]),[msg,setMsg]=useState(''),[err,setErr]=useState(''),
    [busy,setBusy]=useState(false),[query,setQuery]=useState(''),[drag,setDrag]=useState(false);
  const categories=['Electronics','Computers & Accessories','Mobiles','Tablets','Fashion','Home & Kitchen','Beauty','Books','Sports','Other'];
  const load=()=>Promise.all([api.get('/products/mine'),api.get('/orders/mine')]).then(([a,b])=>{setP(a.products);setO(b.orders)}).catch(e=>setErr(e.message));
  useEffect(()=>{load()},[]);
  const reset=()=>{setF({name:'',description:'',price:'',category:'',stock:'',images:''});setFiles([]);setEdit(null);setMsg('');setErr('')};
  const selectFiles=(list)=>{const selected=Array.from(list||[]);if(selected.length>8){setErr('You can upload up to 8 images.');return}const invalid=selected.find(file=>!/^image\/(jpeg|png|webp|gif)$/.test(file.type)||file.size>5*1024*1024);if(invalid){setErr('Each image must be JPG, PNG, WEBP or GIF and no larger than 5 MB.');return}setErr('');setFiles(selected)};
  async function save(e){
    e.preventDefault();setMsg('');setErr('');
    if(!f.name.trim()||!f.description.trim()||!f.category||f.price===''||f.stock===''){setErr('Please complete all required product details.');return}
    if(Number(f.price)<0||Number(f.stock)<0){setErr('Price and stock cannot be negative.');return}
    if(!edit&&!files.length&&!f.images.trim()){setErr('Add at least one product image or image URL.');return}
    setBusy(true);
    try{
      const uploaded=files.length?await api.upload(files):[];
      const urls=f.images.split(',').map(x=>x.trim()).filter(Boolean);
      const b={name:f.name.trim(),description:f.description.trim(),price:Number(f.price),stock:Number(f.stock),category:f.category,images:(files.length?uploaded:urls).slice(0,8)};
      if(edit) await api.patch('/products/'+edit,b); else await api.post('/products',b);
      const wasEdit=Boolean(edit);setF({name:'',description:'',price:'',category:'',stock:'',images:''});setFiles([]);setEdit(null);
      setMsg(wasEdit?'Product updated successfully.':'Product published successfully.');await load();
    }catch(e){setErr(e.message||'Could not publish the product. Please try again.')}finally{setBusy(false)}
  }
  async function del(id){if(!confirm('Remove this product from your catalogue?'))return;try{await api.del('/products/'+id);setMsg('Product removed.');await load()}catch(e){setErr(e.message)}}
  const visible=p.filter(x=>(x.name+' '+x.category).toLowerCase().includes(query.toLowerCase()));
  const totalValue=o.reduce((s,x)=>s+x.total,0),lowStock=p.filter(x=>x.stock>0&&x.stock<=5).length,outOfStock=p.filter(x=>x.stock===0).length;
  return <main className="page seller-page">
    <section className="seller-hero"><div><div className="eyebrow">SELLER HUB · STORE CONTROL</div><h1>Build a store<br/><em>people remember.</em></h1><p>Publish products, keep stock updated and manage incoming orders from one place.</p></div><div className="seller-badge"><span>LIVE STORE</span><strong>{p.length}</strong><small>active products</small></div></section>
    <section className="seller-stats">
      <button type="button" onClick={()=>document.getElementById('catalogue')?.scrollIntoView({behavior:'smooth'})}><strong>{p.length}</strong><span>Products</span><small>In your catalogue</small></button>
      <button type="button"><strong>{o.length}</strong><span>Orders</span><small>Incoming orders</small></button>
      <button type="button"><strong>₹{totalValue.toLocaleString('en-IN')}</strong><span>Order value</span><small>Across all orders</small></button>
      <button type="button" className={lowStock?'attention':''}><strong>{lowStock+outOfStock}</strong><span>Stock alerts</span><small>{outOfStock} out of stock</small></button>
    </section>
    <div className="sellergrid seller-modern">
      <form className="panel product-form" onSubmit={save}>
        <div className="form-title"><div><span className="step">01</span><div><small>PRODUCT LISTING</small><h2>{edit?'Edit product':'Add a new product'}</h2></div></div>{edit&&<button type="button" className="ghost-btn" onClick={reset}>Cancel</button>}</div>
        <label>Product name<input required placeholder="e.g. Wireless Mechanical Keyboard" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label>
        <label>Description<textarea required maxLength="3000" placeholder="Tell customers what makes this product useful..." value={f.description} onChange={e=>setF({...f,description:e.target.value})}/><span className="field-meta">{f.description.length}/3000</span></label>
        <div className="twocol"><label>Price<input type="number" min="0" step="0.01" required placeholder="0.00" value={f.price} onChange={e=>setF({...f,price:e.target.value})}/></label><label>Stock<input type="number" min="0" required placeholder="0" value={f.stock} onChange={e=>setF({...f,stock:e.target.value})}/></label></div>
        <label>Category<select required value={f.category} onChange={e=>setF({...f,category:e.target.value})}><option value="">Choose a category</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label>
        <div className={`upload-zone ${drag?'dragging':''}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);selectFiles(e.dataTransfer.files)}}>
          <div className="upload-icon">↑</div><strong>{files.length?'Replace selected images':'Drop product images here'}</strong><span>or click to browse · JPG, PNG, WEBP or GIF · max 5 MB each</span><input type="file" accept="image/png,image/jpeg,image/webp,image/gif" multiple onChange={e=>selectFiles(e.target.files)}/>
        </div>
        {files.length>0&&<div className="image-preview-grid">{files.map((file,i)=><div className="preview" key={file.name+i}><img src={URL.createObjectURL(file)} alt={file.name}/><button type="button" onClick={()=>setFiles(files.filter((_,n)=>n!==i))}>×</button><span>{file.name}</span></div>)}</div>}
        <label>Image URLs <small>(optional · comma separated)</small><input placeholder="https://..." value={f.images} onChange={e=>setF({...f,images:e.target.value})}/></label>
        {err&&<div className="publish-error"><strong>Couldn't publish</strong><span>{err}</span></div>}{msg&&<div className="publish-success">✓ {msg}</div>}
        <button className="publish-btn" disabled={busy}>{busy?<><span className="spinner"></span>{edit?'Saving changes...':'Publishing product...'}</>:edit?'Save product changes':'Publish product'}</button>
      </form>
      <section className="catalogue" id="catalogue"><div className="catalogue-head"><div><small>YOUR CATALOGUE</small><h2>{p.length?'Products you sell':'Your storefront'}</h2></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search catalogue..."/></div>
        {visible.length?<div className="product-list">{visible.map(x=><article className="seller-product" key={x._id}><div className="seller-product-image">{x.images?.[0]?<img src={mediaUrl(x.images?.[0])} alt={x.name}/>:<span>C</span>}</div><div className="seller-product-info"><div className="product-category">{x.category}</div><h3>{x.name}</h3><p>₹{x.price.toLocaleString('en-IN')} · {x.stock} units</p><div className={`stock-pill ${x.stock===0?'out':x.stock<=5?'low':''}`}>{x.stock===0?'Out of stock':x.stock<=5?'Low stock':'In stock'}</div></div><div className="seller-actions"><button type="button" onClick={()=>{setEdit(x._id);setF({name:x.name,description:x.description,price:x.price,category:x.category,stock:x.stock,images:(x.images||[]).join(',')});setFiles([]);setErr('');setMsg('');window.scrollTo({top:0,behavior:'smooth'})}}>Edit</button><button type="button" className="danger" onClick={()=>del(x._id)}>Remove</button></div></article>)}</div>:<div className="catalogue-empty"><div>＋</div><h3>{query?'No matching products':'Your catalogue is waiting.'}</h3><p>{query?'Try another search.':'Add your first product and it will appear here instantly.'}</p></div>}
      </section>
    </div>
  </main>
}

function Owner(){const[p,setP]=useState([]),[loading,setLoading]=useState(true),[err,setErr]=useState(''),[query,setQuery]=useState(''),[showRemoved,setShowRemoved]=useState(false);const load=()=>api.get('/products/owner/all').then(x=>setP(x.products)).catch(e=>setErr(e.message)).finally(()=>setLoading(false));useEffect(()=>{load()},[]);async function remove(id,name){if(!confirm('Remove “'+name+'” from the marketplace? This will hide it from customers.'))return;try{await api.del('/products/owner/'+id);setP(v=>v.map(x=>x._id===id?{...x,active:false}:x))}catch(e){setErr(e.message)}}const visible=p.filter(x=>showRemoved?!0:x.active).filter(x=>(x.name+' '+(x.category||'')+' '+(x.seller?.name||'')).toLowerCase().includes(query.toLowerCase()));const active=p.filter(x=>x.active).length,removed=p.length-active;return <main className="page owner-page"><section className="owner-hero"><div><small>OWNER CONTROL · MODERATION</small><h1>Keep the marketplace<br/><em>safe & clean.</em></h1><p>Review every listing and remove products that violate marketplace rules or cannot legally be sold.</p></div><div className="owner-lock">OWNER<br/><strong>CONTROL</strong></div></section><section className="owner-stats"><div><strong>{active}</strong><span>Active listings</span></div><div><strong>{removed}</strong><span>Removed listings</span></div><div><strong>{p.length}</strong><span>Total reviewed</span></div></section><div className="owner-toolbar"><div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search product or seller..."/><button className={showRemoved?'selected':''} onClick={()=>setShowRemoved(!showRemoved)}>{showRemoved?'Showing all':'Show removed'}</button></div><small>Moderation actions hide a listing from the public marketplace.</small></div>{err&&<div className="error owner-error">{err}</div>}{loading?<div className="loading">Loading marketplace listings…</div>:visible.length?<section className="owner-list">{visible.map(x=><article className={x.active?'owner-product':'owner-product removed'} key={x._id}><div className="owner-image">{x.images?.[0]?<img src={mediaUrl(x.images[0])} alt=""/>:<span>C</span>}</div><div className="owner-info"><small>{x.category}</small><h3>{x.name}</h3><p>{x.description}</p><div><span>Seller: <b>{x.seller?.name||'Unknown seller'}</b></span><span>₹{Number(x.price).toLocaleString('en-IN')} · {x.stock} in stock</span></div></div><div className="owner-action">{x.active?<><span className="status-live">LIVE</span><button className="remove-btn" onClick={()=>remove(x._id,x.name)}>Remove listing</button></>:<span className="status-removed">REMOVED</span>}</div></article>)}</section>:<div className="empty owner-empty">No listings match your search.</div>}</main>}

export function Providers({children}){return <AuthProvider><CartProvider>{children}</CartProvider></AuthProvider>}
export default function App(){return <Layout><Routes><Route path="/" element={<Home/>}/><Route path="/products/:id" element={<Details/>}/><Route path="/login" element={<Auth/>}/><Route path="/register" element={<Auth register/>}/><Route path="/owner-login" element={<Auth owner/>}/><Route path="/cart" element={<Cart/>}/><Route path="/checkout" element={<Guard role="customer"><Checkout/></Guard>}/><Route path="/orders" element={<Guard><Orders/></Guard>}/><Route path="/notifications" element={<Guard><Notifications/></Guard>}/><Route path="/seller" element={<Guard role="seller"><Seller/></Guard>}/><Route path="/owner" element={<Guard role="owner"><Owner/></Guard>}/></Routes></Layout>}
